version: "3.9"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'
        

volumes:
  mysql:
  redis:
  
services:
  gindemo:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    container_name: gin-demo
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.21       
    container_name: my-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: 'gindemo'
      MYSQL_ROOT_PASSWORD: 'zjw@123456'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      network:
        ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    container_name: my-redis
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - redis:/data
    networks:
      network:
        ipv4_address: 177.7.0.14
